# Generated by Django 2.2.1 on 2019-05-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hurtownie',
            fields=[
                ('nr_hurtowni', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('miasto', models.CharField(max_length=30)),
                ('ulica', models.CharField(max_length=30)),
                ('nr_budynku', models.CharField(max_length=5)),
                ('nr_lokalu', models.CharField(blank=True, max_length=5, null=True)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('data_zalozenia', models.DateField()),
                ('imie_wlasciciela', models.CharField(max_length=20)),
                ('nazwisko_wlasciciela', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nr_hurtowni',),
            },
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('nr_konta', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('haslo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('nr_klienta', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('nr_telefonu', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('firma', models.CharField(blank=True, max_length=30, null=True)),
                ('nr_hurtowni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klient_hurtownia', to='api_hurtownia.Hurtownie')),
                ('nr_konta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klient_konto', to='api_hurtownia.Konto')),
            ],
        ),
    ]
