# Generated by Django 2.2.1 on 2019-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hurtownie',
            name='imie_wlasciciela',
            field=models.CharField(max_length=21),
        ),
    ]
