# Generated by Django 2.2.1 on 2019-05-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0003_auto_20190516_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='nr_konta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klient_konto', to='api_hurtownia.Konto'),
        ),
    ]
