# Generated by Django 2.2.1 on 2019-05-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0004_auto_20190517_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='login',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
