# Generated by Django 2.2.1 on 2019-05-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0005_auto_20190517_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowiska',
            fields=[
                ('nr_stanowiska', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('stanowisko', models.CharField(max_length=30)),
                ('opis', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
