# Generated by Django 2.2.1 on 2019-05-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0007_magazyn_pracownik_wynagrodzenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazyn',
            name='nr_magazynu',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='nr_pracownika',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stanowiska',
            name='nr_stanowiska',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wynagrodzenie',
            name='nr_wynagrodzenia',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
