# Generated by Django 2.2.1 on 2019-05-19 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0008_auto_20190519_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostawca',
            fields=[
                ('nr_dostawcy', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('miasto', models.CharField(max_length=30)),
                ('ulica', models.CharField(max_length=30)),
                ('nr_budynku', models.CharField(max_length=5)),
                ('nr_lokalu', models.CharField(blank=True, max_length=5, null=True)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('nr_telefonu', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('nr_hurtowni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawca_hurtownia', to='api_hurtownia.Hurtownie')),
            ],
        ),
        migrations.CreateModel(
            name='Dzial',
            fields=[
                ('nr_dzialu', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30)),
                ('opis', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('nr_producenta', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30)),
                ('miasto', models.CharField(max_length=30)),
                ('ulica', models.CharField(max_length=30)),
                ('nr_budynku', models.CharField(max_length=5)),
                ('nr_lokalu', models.CharField(blank=True, max_length=5, null=True)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('nr_telefonu', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('nr_produktu', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30)),
                ('opis', models.CharField(blank=True, max_length=300, null=True)),
                ('cena_zakupu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena_sprzedazy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ilosc', models.IntegerField()),
                ('nr_dostawcy', models.ManyToManyField(related_name='produkt_dostawca', to='api_hurtownia.Dostawca')),
                ('nr_hurtowni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkt_hurtownia', to='api_hurtownia.Hurtownie')),
                ('nr_magazynu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkt_magazyn', to='api_hurtownia.Magazyn')),
                ('nr_producenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkt_producent', to='api_hurtownia.Producent')),
            ],
        ),
    ]
