# Generated by Django 2.2.1 on 2019-05-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0009_dostawca_dzial_producent_produkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='nr_produktu',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
