# Generated by Django 2.2.1 on 2019-05-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0010_auto_20190519_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transakcja',
            fields=[
                ('nr_transakcji', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('data_transakcji', models.DateField()),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nr_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transakcja_klient', to='api_hurtownia.Klient')),
            ],
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('nr_faktury', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('data_wystawienia', models.DateField()),
                ('kwota_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kwota_brutto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nr_transakcji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktura_transakcja', to='api_hurtownia.Transakcja')),
            ],
        ),
    ]
