# Generated by Django 2.2.1 on 2019-05-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0011_faktura_transakcja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
