# Generated by Django 2.2.1 on 2019-05-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_hurtownia', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
